### PR TITLE
Gas Card for Mekanism

### PR DESCRIPTION
**Pull request by jfelipearaujo**
The Gas Card can handle all modes and filtering.

The card:

Transferring gases with nodes:

### CODE REVIEW

**Comment by FResetFrisk** [comment]
damn this is nice. how would we access this

**Comment by bstramsek** [comment]
Would love to have this in - however I fear that this implementation would make LaserIO dependable on Mekanism being in a pack. Althogh, I haven't worked with java for a hot minute so maybe imports can now somehow be optional?

Alternatively, if you could put this whole thing in a separate mod as an addon to LaserIO and Mekanism...

**Comment by jfelipearaujo** [comment]
@bstramsek you’re correct. This implementation is adding a high coupling to LaserIO with Mekanism. I don’t know if there’s something to optionally add or not all the implementation that I made, but there is a better solution: an addon API. With an API will be possible to extended and add new features to LaserIO. Without this API it’s hard to create something without coupling the code bases. In the future, when an API comes out I’ll create a properly addon and avoid a high coupling.

**Comment by MichaelHillcox** [comment]
It should be possible to do this with loose coupling, meaning that the items and compatibility added is reliant on the mod being loaded at the same time as LaserIO. I've not had time to fully look into the Dire code but knowing how dire does things, it would mean that you'd either need to create extension functions which would be meh, or you'd need to actually exact each bit of logic out into an API which would likely take quite a bit of work.

**Pull request closed without merging**
