### PR TITLE
Show card type name and color on the card GUI

### PR DESCRIPTION
**Pull request by tdaffin**
I get confused about what card is open so I added a header area to the card GUI with the card name and color.

It looks like this:
Screenshot from 2022-08-13 23-36-03

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
Hi, thanks for showing an interest in the project 🎉 

I like the idea of adding the name and color of the card to the gui but I think we can do it in a less overpowering way. I might suggest something a bit more like this:

https://c.mikey.pro/screenshots/2022/08/Figma_79A071E0-B384-4456-9AD9-9C887BFDF965.png

Just a though, something a little more subtle. I also don't have the MC font on my machine so it'll look a bit strange

**Comment by tdaffin** [comment]
I've been trying a few different layouts.
One thing I've run into is that once I move the top left buttons down there is no more room on the left side for new buttons (see screenshot below with card in 'output' mode where additional buttons show up on the left side).
So, I think it might be a bit more future proof to continue with the 'exterior decordation' approach.
Here is one new layout I came up with:
Screenshot from 2022-08-14 13-41-02
Note that this code has not yet been pushed to this branch. Just getting your feedback before proceeding.

**Comment by Direwolf20-MC** [comment]
Let me think about this one :). I do like the idea of showing more clearly which card you are currently working on - but I might want to take a diff approach.

**Comment by tdaffin** [comment]
Sounds good.  This was an interesting journey into what is possible in Minecraft GUI :)

**Pull request closed without merging**
