### PR TITLE
Translations for version 1.3.1 and translation pt_br to the Patchouli Book

### PR DESCRIPTION
**Pull request by jfelipearaujo**
Hi Dire,

I've updated the pt-br language file for mod version 1.3.1.

Hope you enjoy.

Thanks.

### CODE REVIEW

**Comment by jfelipearaujo** [comment]
Hi Dire,

I've updated the pt-br language file.

Hope you enjoy.

Thanks.

**Comment by Direwolf20-MC** [comment]
Thank you!! I’ll get this merged soon! :)

**Comment by jfelipearaujo** [comment]
@Direwolf20-MC I started translating the patchouli book and would like to test if the translations (and localizations) are making sense. Is there any way (easy and practical) to test it?

**Comment by Direwolf20-MC** [comment]
If you go into the game from your dev environment and go into creative mode - on the first page of the book there will be a button that refreshes the book. I forget what it’s called.

**Comment by jfelipearaujo** [comment]
I got it. I'll setup my dev environment. Thanks!

**Comment by jfelipearaujo** [comment]
Hi Dire,

I added the pt_br version to the Patchouli Book.

Thanks.

**Comment by Direwolf20-MC** [comment]
Thank you again for all this hard work!! :)

**Pull request merged**
